# Generated by Django 4.2.10 on 2024-02-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="backend_tag_name_194adf_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "sku",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[("low", "Low"), ("empty", "Empty")], max_length=20
                    ),
                ),
                ("available_stock", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="items", to="backend.tag"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="backend.user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="backend_cat_name_4dc900_idx"),
        ),
    ]
